apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: 10052011-myapi
  namespace: observability
  labels:
    project: myapi
    team: 10052011
spec:
  title: "10052011 / myapi"
  instanceSelector:
    matchLabels:
      dashboards: grafana
